apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: userdashboard
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  USER_SERVICE_URL: "http://user-service:4002"
  ANALYTICS_SERVICE_URL: "http://analytics-service:4003"
